<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class entitiesWebsiteProxy extends \entities\Website implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function get_id()
    {
        $this->_load();
        return parent::get_id();
    }

    public function set_id($id)
    {
        $this->_load();
        return parent::set_id($id);
    }

    public function get_users()
    {
        $this->_load();
        return parent::get_users();
    }

    public function set_users($users)
    {
        $this->_load();
        return parent::set_users($users);
    }

    public function get_user_groups()
    {
        $this->_load();
        return parent::get_user_groups();
    }

    public function set_user_groups($user_groups)
    {
        $this->_load();
        return parent::set_user_groups($user_groups);
    }

    public function get_domains()
    {
        $this->_load();
        return parent::get_domains();
    }

    public function set_domains($domains)
    {
        $this->_load();
        return parent::set_domains($domains);
    }

    public function get_templates()
    {
        $this->_load();
        return parent::get_templates();
    }

    public function set_templates($templates)
    {
        $this->_load();
        return parent::set_templates($templates);
    }

    public function get_modules()
    {
        $this->_load();
        return parent::get_modules();
    }

    public function set_modules($modules)
    {
        $this->_load();
        return parent::set_modules($modules);
    }

    public function get_pages()
    {
        $this->_load();
        return parent::get_pages();
    }

    public function set_pages($pages)
    {
        $this->_load();
        return parent::set_pages($pages);
    }

    public function get_products()
    {
        $this->_load();
        return parent::get_products();
    }

    public function set_products($products)
    {
        $this->_load();
        return parent::set_products($products);
    }

    public function get_categories()
    {
        $this->_load();
        return parent::get_categories();
    }

    public function set_categories($categories)
    {
        $this->_load();
        return parent::set_categories($categories);
    }

    public function get_hash()
    {
        $this->_load();
        return parent::get_hash();
    }

    public function set_hash($hash)
    {
        $this->_load();
        return parent::set_hash($hash);
    }

    public function get_created()
    {
        $this->_load();
        return parent::get_created();
    }

    public function set_created($created)
    {
        $this->_load();
        return parent::set_created($created);
    }

    public function get_name()
    {
        $this->_load();
        return parent::get_name();
    }

    public function set_name($name)
    {
        $this->_load();
        return parent::set_name($name);
    }

    public function get_company()
    {
        $this->_load();
        return parent::get_company();
    }

    public function set_company($company)
    {
        $this->_load();
        return parent::set_company($company);
    }

    public function get_company_reg()
    {
        $this->_load();
        return parent::get_company_reg();
    }

    public function set_company_reg($company_reg)
    {
        $this->_load();
        return parent::set_company_reg($company_reg);
    }

    public function get_address()
    {
        $this->_load();
        return parent::get_address();
    }

    public function set_address($address)
    {
        $this->_load();
        return parent::set_address($address);
    }

    public function get_zip()
    {
        $this->_load();
        return parent::get_zip();
    }

    public function set_zip($zip)
    {
        $this->_load();
        return parent::set_zip($zip);
    }

    public function get_city()
    {
        $this->_load();
        return parent::get_city();
    }

    public function set_city($city)
    {
        $this->_load();
        return parent::set_city($city);
    }

    public function get_email()
    {
        $this->_load();
        return parent::get_email();
    }

    public function set_email($email)
    {
        $this->_load();
        return parent::set_email($email);
    }

    public function get_telephone()
    {
        $this->_load();
        return parent::get_telephone();
    }

    public function set_telephone($telephone)
    {
        $this->_load();
        return parent::set_telephone($telephone);
    }

    public function get_tracking_code()
    {
        $this->_load();
        return parent::get_tracking_code();
    }

    public function set_tracking_code($tracking_code)
    {
        $this->_load();
        return parent::set_tracking_code($tracking_code);
    }

    public function get_tracking_code_invoice()
    {
        $this->_load();
        return parent::get_tracking_code_invoice();
    }

    public function set_tracking_code_invoice($tracking_code_invoice)
    {
        $this->_load();
        return parent::set_tracking_code_invoice($tracking_code_invoice);
    }

    public function get_template()
    {
        $this->_load();
        return parent::get_template();
    }

    public function set_template($template)
    {
        $this->_load();
        return parent::set_template($template);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'users', 'user_groups', 'domains', 'templates', 'modules', 'pages', 'products', 'categories', 'hash', 'created', 'name', 'company', 'company_reg', 'address', 'zip', 'city', 'email', 'telephone', 'tracking_code', 'tracking_code_invoice', 'template');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}